---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/items":
    get:
      summary: all items
      tags:
      - Item
      security:
      - Bearailsrer: []
      consumes:
      - application/json
      responses:
        '200':
          description: successful
    post:
      summary: create item
      tags:
      - Item
      security:
      - Bearer: []
      consumes:
      - application/json
      parameters:
      - name: item
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            description:
              type: string
            image:
              type: string
            price:
              type: integer
            color:
              type: string
            user_id:
              type: integer
          required:
          - name
          - description
          - image
          - price
          - color
          - user_id
      responses:
        '201':
          description: created
  "/items/{id}":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: item details
      tags:
      - Item
      security:
      - Bearer: []
      responses:
        '200':
          description: successful
    delete:
      summary: item delete
      tags:
      - Item
      security:
      - Bearer: []
      responses:
        '204':
          description: successful
  "/reservations":
    get:
      summary: all reservations
      tags:
      - Reservation
      security:
      - Bearer: []
      consumes:
      - application/json
      responses:
        '200':
          description: successful
    post:
      summary: create reservation
      tags:
      - Reservation
      security:
      - Bearer: []
      consumes:
      - application/json
      parameters:
      - name: reservation
        in: body
        schema:
          type: object
          properties:
            city:
              type: string
            date:
              type: string
            item_id:
              type: integer
            user_id:
              type: integer
          required:
          - city
          - date
          - item_id
          - user_id
      responses:
        '201':
          description: created
  "/reservations/{id}":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: reservations details
      tags:
      - Reservation
      security:
      - Bearer: []
      responses:
        '200':
          description: successful
    delete:
      summary: delete reservation
      tags:
      - Reservation
      security:
      - Bearer: []
      responses:
        '204':
          description: successful
  "/register":
    post:
      summary: Creates a new account
      tags:
      - Auth
      consumes:
      - application/json
      parameters:
      - name: form
        in: body
        required: true
        schema:
          type: object
          properties:
            user:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
          required:
          - name
          - email
          - password
      responses:
        '201':
          description: user created
        '422':
          description: invalid request
  "/login":
    post:
      summary: Authenticate user
      tags:
      - Auth
      consumes:
      - application/json
      parameters:
      - name: form
        in: body
        required: true
        schema:
          type: object
          properties:
            user:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
          required:
          - name
          - email
          - password
      responses:
        '201':
          description: logged in
        '401':
          description: invalid request
  "/logout":
    delete:
      summary: Log out current user
      tags:
      - Auth
      security:
      - Bearer: []
      consumes:
      - application/json
      responses:
        '204':
          description: success
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:300
